CREATE DATABASE testapimysql;

USE testapimysql;

CREATE TABLE IF NOT EXISTS users(
	idUsuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

SELECT * FROM users;